<Project>
  <PropertyGroup>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFrameworks>net462;netstandard2.0;net10.0</TargetFrameworks>
    <Company>SIL Global</Company>
    <Authors>SIL Global</Authors>
    <Product>SIL.PasswordStore</Product>
    <Copyright>Copyright © 2022-2026 SIL Global</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/sillsdev/SIL.PasswordStore</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)/SIL.PasswordStore.snk</AssemblyOriginatorKeyFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <AppendToReleaseNotesProperty><![CDATA[
See full changelog at https://github.com/sillsdev/SIL.PasswordStore/blob/master/CHANGELOG.md]]>
    </AppendToReleaseNotesProperty>
    <UseFullSemVerForNuGet>false</UseFullSemVerForNuGet>
  </PropertyGroup>
</Project>